### ISSUE TITLE
4 phpunit tests failures

### ISSUE THREAD

**Issue by jgpATs2w** [Learnosity/learnosity-sdk-php#11]
Hi, I'm new to learnosity but interested to prepare a demo for my customers. I've downloaded the repo, and phpunit test is failing:
..FF........F..........F......................................... 65 / 73 ( 89%)
........

Time: 2.06 seconds, Memory: 10.00Mb

There were 4 failures:

1) tests\LearnositySdk\Request\InitTest::testGenerate with data set #0 ('security={"consumer_key":"yis...on=get', LearnositySd

k\Request\Init Object (...))
Array (...) does not match expected type "string".

/var/www/html/learnosity-sdk-php/src/tests/LearnositySdk/Request/InitTest.php:100

2) tests\LearnositySdk\Request\InitTest::testGenerate with data set #1 ('security={"consumer_key":"yis...n=post', LearnositySd
k\Request\Init Object (...))
Array (...) does not match expected type "string".

/var/www/html/learnosity-sdk-php/src/tests/LearnositySdk/Request/InitTest.php:100

3) tests\LearnositySdk\Request\InitTest::testConstructor with data set #8 ('data', array('yis0TYCu7U9V4o7M', 'localhost'), '74
c5fd430cf1242a527f6223aebd4...64be22', '{{"a":"b"]}', 'get', null, '\LearnositySdk\Exceptions\Val...eption', 'Invalid data, pl
ease check yo...d JSON')

**Comment by shtrom** [comment]
Hey,

Could you try this branch: https://github.com/Learnosity/learnosity-sdk-php/pull/17

**Comment by shtrom** [comment]
Actually, it's merged in `master` now.
